name: Bug report
description: Create a report to help us improve
title: '[BUG]'

body:
  - type: markdown
    id: bug-info
    attributes:
      value: "## BUG Infomation"
  - type: textarea
    id: bug-desc
    attributes:
      label: "Describe the bug"
      description: "A clear and concise description of what the bug is."
    validations:
      required: true
    
  - type: textarea
    id: bug-screenshots
    attributes:
      label: "Screenshots"
      description: "If applicable, add screenshots to help explain your problem."
    validations:
      required: true

  - type: textarea
    id: waydroid-env-info
    attributes:
      label: "General information (please complete the following information):"
      placeholder: "- Waydroid tools Version [e.g. 1.1.0] \
    
 - Waydroid Images Version [e.g. VANILLA 20211021], or `system_datetime`/`vendor_datetime` from `/var/lib/waydroid/waydroid.cfg`"
    validations:
      required: true
   
  - type: textarea
    id: desktop-env-info
    attributes:
      label: "Desktop (please complete the following information):"
      placeholder: "- OS: [e.g. Ubuntu 20.04 x64] \
 - GPU: [e.g. AMD Radeon™ RX 5700] \

 - Kernel version: [e.g. Generic 5.4.x] \
 
 - Host mesa version: [e.g. mesa 2.2] \
 
 - Desktop: [e.g. Gnome 40.x.x]"
    validations:
      required: false
  - type: textarea
    id: handset-env-info
    attributes:
      label: "Smartphone (please complete the following information):"
      placeholder: " - Device: [e.g. Pixel 3a] \
 
 - OS: [e.g. Ubuntu touch OTA19] \
  
 - Mainline or Halium [e.g. Halium 9] \
  
 - Kernel version: [e.g. 4.14.x]"
    validations:
      required: false
   
- type: textarea
    id: additional-info
    attributes:
      label: "Additional Information"
      description: "Add any other context about the problem here."
    validations:
      required: false

- type: textarea
    id: bug-log
    attributes:
      label: "Logs (please upload as file)"
      placeholder: "- Prop file, located at `/var/lib/waydroid/waydroid.prop`. In case that doesn't exist, use `/var/lib/waydroid/waydroid_base.prop` instead \
  
 - Log file, located at `/var/lib/waydroid/waydroid.log` \
  
 - *Full* (not partial) output of `waydroid logcat` while Waydroid is running \

 - Output of `dmesg`"
    validations:
      required: true
